title: Learning Cheat Sheets
description: Um site com vários cheatsheets para aprender o mais rápido possível e para uso de referência.
collections:
  cheatsheets:
    output: true
    permalink: /cheatsheets/:name/
markdown: kramdown
exclude:
  - scripts/
  - .github/
  - node_modules/
  - package.json
  - package-lock.json
  - LICENSE
  - README.md
