name: Build Cheatsheets

on:
  push:
    paths:
      - 'cheatsheets/**.md'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install markdown-pdf
        run: npm install -g markdown-pdf

      - name: Create output dirs
        run: mkdir -p assets/html assets/pdfs

      - name: Convert MD to HTML & PDF
        run: |
          for file in cheatsheets/*.md; do
            filename=$(basename "$file" .md)
            markdown-pdf "$file" -o "assets/pdfs/$filename.pdf"
            markdown-pdf "$file" --html -o "assets/html/$filename.html"
          done

      - name: List generated files
        run: ls -R assets
